Repository IIC3745-Testing-Grupo3/IIC3745-Grupo3-ProyectoA, pull requests merged in 2021-10, with the labels that each got.

#11 Remove paths in github action
  .github/workflows/rubyworkflow.yml
Labels: bugfix

#10 Fix rubocop check in Rakefile
  Rakefile
Labels: bugfix

#8 Add minesweeper modelling
  Gemfile
  Gemfile.lock
  README.md
  boards/board_01.txt
  src/controller/game_controller.rb
  src/controller/minesweeper.rb
  src/main.rb
  src/model/board.rb
  src/model/cell.rb
  src/utils/board_creators.rb
  src/view/minesweeper_display.rb
Labels: feature, improvement

#14 Change obeserver to observer
  src/view/game_view.rb
Labels: bugfix

#15 Change cell to_s method when the cell is revealed
  Rakefile
  src/model/cell.rb
  test/model/cell_test.rb
Labels: feature, test, improvement

#16 Improve print board method
  src/model/cell.rb
  src/view/game_view.rb
Labels: improvement

#17 Add basic game logic
  src/controller/game_controller.rb
  src/main.rb
  src/model/board.rb
  src/view/game_view.rb
Labels: feature, improvement

#18 End game if a cell with a B is selected
  src/controller/game_controller.rb
  src/view/game_view.rb
Labels: feature, improvement

#19 Win game if all no-bomb cells had been reveal
  src/controller/game_controller.rb
  src/model/board.rb
  src/view/game_view.rb
Labels: feature, improvement

#20 Fix board ordinates values
  src/controller/game_controller.rb
  src/view/game_view.rb
Labels: bugfix, improvement

#21 New pretty way to test boards
  Rakefile
  src/model/board.rb
  test/model/board_test.rb
Labels: test, improvement

#23 Add unit tests for utils "board_creators.rb"
  Rakefile
  test/utils/board_creators_test.rb
Labels: test, improvement

#25 Add GameController tests
  Rakefile
  src/controller/game_controller.rb
  test/controller/game_controller_test.rb
Labels: test

#26 Fix/exit game option
  src/controller/game_controller.rb
  test/controller/game_controller_test.rb
Labels: bugfix

#29 Fix bug when input is using downcase letter
  src/controller/game_controller.rb
  test/controller/game_controller_test.rb
Labels: bugfix, improvement

#30 Add unit tests for observer classes
  Rakefile
  src/observer/observable.rb
  test/observer/observable_test.rb
  test/observer/observer_test.rb
Labels: test, improvement

#32 Update readme with setup instructions and workflow
  README.md
Labels: documentation

#37 Add final tests for board check_surrounding method
  test/model/board_test.rb
Labels: test

#38 fix(input-bug): Fix bug when input is out of range
  Rakefile
  src/controller/game_controller.rb
  src/utils/validations.rb
  src/view/game_view.rb
  test/controller/game_controller_test.rb
  test/utils/validations_test.rb
Labels: bugfix

#39 Add video url to readme
  README.md
Labels: documentation

#40 Add images to readme with coverage and static analysis
  README.md
  images/coverage.png
  images/sonarcloud.png
Labels: documentation
