Repository IIC3745-Testing-Grupo3/IIC3745-Grupo3-ProyectoA, pull requests merged in 2021-09, with the labels that each got.

#3 Fix lockfile problem in linux based OS
  Gemfile.lock
Labels: bug, enhancement

#1 Add github actions
  .github/workflows/rubyworkflow.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Rakefile
  src/controller/minesweeper.rb
  src/main.rb
  src/model/board.rb
  src/view/minesweeper_display.rb
  test/example_test.rb
  test/test_helper.rb
Labels: enhancement

#4 Add a pull request template
  .github/pull_request_template.md
Labels: workflow

#5 Add a bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: workflow

#7 Add static analysis to the project
  .gitignore
  sonar-project.properties
Labels: workflow, test, improvement
